CREATE TABLE t_analytics_contact
(
    id bigint not null,
    first_name text,
    middle_name text,
    last_name text,
    contact_type text,
    organization_name text,
    date_of_birth text,
    deceased boolean,
    employer text,
    gender text,
    industry text,
    language text,
    occupation text,
    contact_methods text,
    mark text,
    leaning text,
    cases_filed int,
    cases_closed int,
    etags text,
    survey_responses text,
    federal_elector_id bigint,
    federal_poll text,
    federal_riding text,
    federal_sequence_number text,
    has_email boolean,
    townhouse_or_apartment text,
    civic_address_type text,
    civic_address_city text,
    civic_address_province text,
    civic_address_country text,
    civic_address_postal_code text,
    civic_address_street_type text,
    civic_address_township text,
    location text
    
);

